Trainer:
  loss:
    name:
        class_name: SparseCategoricalCrossentropy
        config:
          from_logits: True
  metric: 
    name: 'CategoricalAccuracy'
  optimizer:
    name: 'SGD'
    learning_rate: 0.01
  dataset:
    name: 'cifar10'
    batch_size: 128
    epoch: 1000
    path_to_data: 'dataset/image/cifar10/labeled.csv'
  model:
    name: 'DNN'
    units: [64,32,16,10]
    activations: [relu,relu,relu,softmax]
    fuse_models: 1

Plotter:
  task: "1d"
  num_evaluate: 100
  step: 1e-3
  save_directions: False
  load_directions: False
  save_file: ./dataset/result/1d_cifar10_dnn_100
