Trainer:
  loss:
    name:
        class_name: SparseCategoricalCrossentropy
        config:
          from_logits: False
  metric: 
    name: 'SparseCategoricalAccuracy'
  optimizer:
    name: 'Adam'
    learning_rate: 0.001
  dataset:
    name: 'cifar10'
    batch_size: 2048
    epoch: 100
    path_to_data: './dataset/image/cifar10/'
  model:
    name: 'ResNet50'
    save_path_to_model: './dataset/model/cifar10_resnet50/'
  others:
    path_to_log: './dataset/logs/cifar10_resnet50/'

Plotter:
  task: "1d"
  num_evaluate: 1000
  step: 1e-3
  fuse_nums: None
  save_directions: False
  load_directions: False
  path_to_adapt_label: './dataset/image/cifar10_resnet50/'
  save_file: ./dataset/result/1d_cifar10_resnet50_1w
