Trainer:
  loss:
    name:
        class_name: SparseCategoricalCrossentropy
        config:
          from_logits: False
          reduction: auto
  metric: 
    name: 'SparseCategoricalAccuracy'
  optimizer:
    name: 'Adam'
    learning_rate: 0.001
  dataset:
    name: 'cifar10'
    batch_size: 64
    epoch: 1
    path_to_data: './dataset/image/cifar10_resnet50/'
  model:
    name: 'ResNet50'
    save_path_to_model: './dataset/model/cifar10_resnet50/'
  others:
    # distribute: False
    restore_from_weight: True
    path_to_log: './dataset/logs/cifar10_resnet50/'

Plotter:
  task: "2d"
  num_evaluate: [500,500]
  step: [1e-2,1e-2]
  save_directions: False
  load_directions: False
  fuse_nums: None
  # localminima: True
  path_to_adapt_label: './dataset/image/cifar10_resnet50/'
  save_file: ./dataset/result/2d_cifar10_resnet50_25w
