Trainer:
  loss:
    name:
        class_name: SparseCategoricalCrossentropy
        config:
          from_logits: False
  metric: 
    name: 'SparseCategoricalAccuracy'
  optimizer:
    name: 'Adam'
    learning_rate: 
      class_name: "ExponentialDecay"
      config:
        initial_learning_rate: 0.001
        decay_steps: 3000
        decay_rate: 0.96 
  dataset:
    name: 'cifar10'
    batch_size: 512
    epoch: 300
    path_to_data: './dataset/image/cifar10_dnn_acc/'
  model:
    name: 'DNN'
    units: [64,32,16,10]
    activations: [relu,relu,relu,softmax]
    save_path_to_model: './dataset/model/cifar10_dnn/'
  others:
    distribute: False
    path_to_log: './dataset/logs/cifar10_dnn/'

Plotter:
  task: "2d"
  num_evaluate: [2000,2000]
  step: [1e-3,1e-3]
  save_directions: False
  load_directions: False
  fuse_nums: None
  path_to_adapt_label: './dataset/image/cifar10_dnn_acc/'
  save_file: ./dataset/result/2d_cifar10_dnn_400w_acc
