Trainer:
  loss:
    name:
        class_name: SparseCategoricalCrossentropy
        config:
          from_logits: False
          reduction: auto
  metric: 
    name: 'SparseCategoricalAccuracy'
  optimizer:
    name: 'Adam'
    learning_rate: 0.001
  dataset:
    name: 'cifar10'
    batch_size: 256
    epoch: 200
    path_to_data: './dataset/image/cifar10_cnn/'
  model:
      name: 'CNN'
      kernels: [3,3,3,3]
      filters: [64,32,16,8]
      activations: [relu,relu,relu,relu]
      classes: 10
      tail_acts: softmax
      save_path_to_model: './dataset/model/cifar10_cnn/'
  others:
    distribute: False
    path_to_log: './dataset/logs/cifar10_cnn/'

Plotter:
  task: "2d"
  num_evaluate: [500,500]
  step: [1e-2,1e-2]
  save_directions: False
  load_directions: False
  fuse_nums: None
  path_to_adapt_label: './dataset/image/cifar10_cnn/'
  save_file: ./dataset/result/2d_cifar10_cnn_25w
